

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AutoCinema.DataBase
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CinemaDataContainer : DbContext
{
        private static CinemaDataContainer _context;

        public CinemaDataContainer()
            : base("name=CinemaDataContainer")
        {
        }

        public static CinemaDataContainer GetContext()
        {
            if (_context == null)
                _context = new CinemaDataContainer();

            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Билеты> Билеты { get; set; }

    public virtual DbSet<Бронь> Бронь { get; set; }

    public virtual DbSet<Залы> Залы { get; set; }

    public virtual DbSet<Пользователи> Пользователи { get; set; }

    public virtual DbSet<РазмерыЗалов> РазмерыЗалов { get; set; }

    public virtual DbSet<Сеансы> Сеансы { get; set; }

    public virtual DbSet<СтоимостьБилетов> СтоимостьБилетов { get; set; }

    public virtual DbSet<Фильмы> Фильмы { get; set; }

}

}

