//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCinema.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Билеты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Билеты()
        {
            this.Бронь1 = new HashSet<Бронь>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDСеанса { get; set; }
        public Nullable<int> IDЗала { get; set; }
        public Nullable<int> Ряд { get; set; }
        public Nullable<int> Место { get; set; }
        public Nullable<bool> Бронь { get; set; }
    
        public virtual Залы Залы { get; set; }
        public virtual Сеансы Сеансы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бронь> Бронь1 { get; set; }
    }
}
