
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AutoCinema.DataBase
{

using System;
    using System.Collections.Generic;
    
public partial class Бронь
{

    public int ID { get; set; }

    public Nullable<int> IDБилета { get; set; }

    public string ФИО { get; set; }

    public string Телефон { get; set; }



    public virtual Билеты Билеты { get; set; }

}

}
