//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCinema.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class СтоимостьБилетов
    {
        public int ID { get; set; }
        public Nullable<int> IDСеанса { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    
        public virtual Сеансы Сеансы { get; set; }
    }
}
